services:
  _defaults:
    autowire: true
    autoconfigure: true

  Customer\:
    resource: '../../src/Customer/'
    exclude:
      - '../../src/Domain/Entity/'
      - '../../src/Customer/Infrastructure/Database/ORM/Doctrine/Entity/'
      - '../../src/Kernel.php'
      - '../../src/Tests/'

  Customer\Infrastructure\Controller\:
    resource: '../../src/Customer/Infrastructure/Controller/'
    tags: [ 'controller.service_arguments' ]